import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import { format } from 'date-fns'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const periodTime = 60 * 25
  const [ timer, setTimer ] = useState(periodTime)
  const [ timeLeft, setTimeLeft ] = useState(format(timer * 1000, 'mm:ss'))
  const [ start, setStart ] = useState(false)

 if(start){
  useEffect(() => {
    setTimeout(() => {
      setTimer(timer - 1)
      setTimeLeft(format(timer * 1000, 'mm:ss'))
    }, 1000)
  }, [timer])
 }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Hello world</h1>
        <span>{timeLeft}</span>
      </div>
    </>
  )
}
