import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import { format } from 'date-fns'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const periodTime = 60 * 25
  const longTime = 60 * 10
  const shortTime = 60 * 5
  
  const [ baseTime, setBaseTime ] = useState(periodTime)
  const [ timer, setTimer ] = useState(baseTime)
  const [ timeLeft, setTimeLeft ] = useState(format(periodTime * 1000, 'mm:ss'))
  const [ start, setStart ] = useState(false)
  const [ storedTimeout, setStoredTimeout] = useState(null)

  useEffect(() => {
    if (start) {
      setStoredTimeout(setTimeout(() => {
        setTimer(timer - 1)
        setTimeLeft(format(timer * 1000, 'mm:ss'))
      }, 1000))
    } else {
      clearTimeout(storedTimeout)
    }
  }, [timer, start])

  function resetTime() {
    setTimer(periodTime)
    setTimeLeft(format(periodTime * 1000, 'mm:ss'))
    setStart(false)
  }
    
  return (
    <>
      <Head>
        <title>Pomodoro: {timeLeft}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Hello world</h1>
        <button>25</button>
        <button>10</button>
        <button>5</button>
        <hr />
        <span>{timeLeft}</span>
        <hr />
        <button onClick={() => setStart(true)}>Começar</button>
        <button onClick={() => setStart(false)}>Pausar</button>
        <button onClick={() => resetTime()}>Reiniciar</button>
      </div>
    </>
  )
}
